Adding usage help to administrator commands.

diff --git a/system/bin/gislab-clients-allowed b/system/bin/gislab-clients-allowed
--- a/system/bin/gislab-clients-allowed
+++ b/system/bin/gislab-clients-allowed
@@ -9,7 +9,35 @@ then
 	source /vagrant/config-user.cfg
 fi
 
-echo -e "\n[GIS.lab]: Creating allowed MACs list ..."
+
+# usage
+function usage() {
+	echo "USAGE: $(basename $0) [OPTIONS]"
+	echo "Enable GIS.lab client MAC addresses specified in GISLAB_CLIENTS_ALLOWED."
+	echo -e "\nOPTIONS
+	-h, --help      display this help
+	"
+	exit 0
+}
+
+
+# options
+TEMP=`getopt --options hp: --longoptions password: \
+	-n $(basename $0) -- "$@"`
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; fi
+eval set -- "$TEMP"
+
+while true ; do
+        case "$1" in
+				-h|--help) usage ; exit 1 ; shift 2 ;;
+                --) shift ; break ;;
+                *) echo "Internal error!" ; exit 1 ;;
+        esac
+done
+
+
+echo -e "\n[GIS.lab]: Enabled MACs list ..."
 
 echo "# This file was automatically generated by GIS.lab script ($(date))." > /etc/ltsp/dhcpd-clients-allowed.conf
 echo "group {" >> /etc/ltsp/dhcpd-clients-allowed.conf
diff --git a/system/bin/gislab-deluser b/system/bin/gislab-deluser
--- a/system/bin/gislab-deluser
+++ b/system/bin/gislab-deluser
@@ -3,19 +3,41 @@
 
 set -e
 
-# test if account name given as parameter
-if [ $# -eq 0 ]
-then
-	echo "Account name is required!"
-	exit 0
-fi
-
 # source configuration files
 source /vagrant/config.cfg
 if [ -f /vagrant/config-user.cfg ]
 then
 	source /vagrant/config-user.cfg
 fi
+
+
+# usage
+function usage() {
+	echo "USAGE: $(basename $0) [OPTIONS] username"
+	echo "Delete GIS.lab user account."
+	echo -e "\nOPTIONS
+	-h, --help      display this help
+	"
+	exit 0
+}
+
+
+# options
+TEMP=`getopt --options hp: --longoptions password: \
+	-n $(basename $0) -- "$@"`
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; fi
+eval set -- "$TEMP"
+
+while true ; do
+        case "$1" in
+				-h|--help) usage ; exit 1 ; shift 2 ;;
+                --) shift ; break ;;
+                *) echo "Internal error!" ; exit 1 ;;
+        esac
+done
+if [ $# -eq 0 ]; then usage; exit 0; fi # test if user name given
+
 
 # remove account
 echo -e "\n[GIS.lab]: Removing GIS.lab user accounts ..."
@@ -29,5 +51,6 @@ rm -rf /storage/share/$1 # NFS directory
 
 
 echo -e "\n[GIS.lab]: Done."
+
 
 # vim: set ts=4 sts=4 sw=4 noet:
diff --git a/system/bin/gislab-install-client b/system/bin/gislab-install-client
--- a/system/bin/gislab-install-client
+++ b/system/bin/gislab-install-client
@@ -3,13 +3,42 @@
 
 set -e
 
-DATETIME=$(date +"%Y-%m-%d-%T")
 
 source /vagrant/config.cfg
 if [ -f /vagrant/config-user.cfg ]
 then
 	source /vagrant/config-user.cfg
 fi
+
+
+# usage
+function usage() {
+	echo "USAGE: $(basename $0) [OPTIONS]"
+	echo "Install GIS.lab client image."
+	echo -e "\nOPTIONS
+	-h, --help      display this help
+	"
+	exit 0
+}
+
+
+# options
+TEMP=`getopt --options hp: --longoptions password: \
+	-n $(basename $0) -- "$@"`
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; fi
+eval set -- "$TEMP"
+
+while true ; do
+        case "$1" in
+				-h|--help) usage ; exit 1 ; shift 2 ;;
+                --) shift ; break ;;
+                *) echo "Internal error!" ; exit 1 ;;
+        esac
+done
+
+
+DATETIME=$(date +"%Y-%m-%d-%T")
 
 echo -e "\n[GIS.lab]: Installing client image ..."
 
